/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : ExtIntLdd2.c
**     Project     : ProcessorExpert
**     Processor   : MK20DX128VLH5
**     Component   : ExtInt_LDD
**     Version     : Component 02.156, Driver 01.02, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-12-15, 00:20, # CodeGen: 20
**     Abstract    :
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
**     Settings    :
**          Component name                                 : ExtIntLdd2
**          Pin                                            : PTA12/FTM1_CH0/I2S0_TXD0/FTM1_QD_PHA
**          Pin signal                                     : 
**          Generate interrupt on                          : both edges
**          Interrupt                                      : INT_PORTA
**          Interrupt priority                             : medium priority
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : yes
**          Threshold level                                : 0
**     Contents    :
**         Init    - LDD_TDeviceData* ExtIntLdd2_Init(LDD_TUserData *UserDataPtr);
**         Enable  - void ExtIntLdd2_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable - void ExtIntLdd2_Disable(LDD_TDeviceData *DeviceDataPtr);
**         GetVal  - bool ExtIntLdd2_GetVal(LDD_TDeviceData *DeviceDataPtr);
**         SetEdge - LDD_TError ExtIntLdd2_SetEdge(LDD_TDeviceData *DeviceDataPtr, uint8_t Edge);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file ExtIntLdd2.c
** @version 01.02
** @brief
**         This component, "ExtInt_LDD", provide a low level API 
**         for unified access of external interrupts handling
**         across various device designs.
**         The component uses one pin which generates interrupt on 
**         selected edge.
*/         
/*!
**  @addtogroup ExtIntLdd2_module ExtIntLdd2 module documentation
**  @{
*/         

/* MODULE ExtIntLdd2. */

#include "HallB.h"
#include "ExtIntLdd2.h"
/* {Default RTOS Adapter} No RTOS includes */

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  uint32_t IrqConfig;                  /* Interrupt Configuration */
  LDD_TUserData *UserData;             /* RTOS device data structure */
} ExtIntLdd2_TDeviceData, *ExtIntLdd2_TDeviceDataPtr; /* Device data structure type */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static ExtIntLdd2_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/* {Default RTOS Adapter} Global variable used for passing a parameter into ISR */
static ExtIntLdd2_TDeviceData * INT_PORTA__DEFAULT_RTOS_ISRPARAM;

/*
** ===================================================================
**     Method      :  ExtIntLdd2_Init (component ExtInt_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* ExtIntLdd2_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  ExtIntLdd2_TDeviceData *DeviceDataPrv;

  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Store the UserData pointer */
  DeviceDataPrv->UserData = UserDataPtr;
  /* Save the IRQ configuration */
  DeviceDataPrv->IrqConfig = PORT_PDD_INTERRUPT_ON_RISING_FALLING;
  /* Interrupt vector(s) allocation */
  /* {Default RTOS Adapter} Set interrupt vector: IVT is static, ISR parameter is passed by the global variable */
  INT_PORTA__DEFAULT_RTOS_ISRPARAM = DeviceDataPrv;
  /* Clear interrupt status flag */
  PORTA_ISFR = PORT_ISFR_ISF(0x1000);                                   
  /* Initialization of Port Control registers */
  /* PORTA_PCR12: ISF=0,IRQC=0x0B,MUX=1 */
  PORTA_PCR12 = (uint32_t)((PORTA_PCR12 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_IRQC(0x04) |
                 PORT_PCR_MUX(0x06)
                )) | (uint32_t)(
                 PORT_PCR_IRQC(0x0B) |
                 PORT_PCR_MUX(0x01)
                ));                                  
  /* NVICIP40: PRI40=0x80 */
  NVICIP40 = NVIC_IP_PRI40(0x80);                                   
  /* NVICISER1: SETENA|=0x0100 */
  NVICISER1 |= NVIC_ISER_SETENA(0x0100);                                   
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_ExtIntLdd2_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  ExtIntLdd2_Enable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Enable the component - the external events are accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void ExtIntLdd2_Enable(LDD_TDeviceData *DeviceDataPtr)
{
  ExtIntLdd2_TDeviceData *DeviceDataPrv = (ExtIntLdd2_TDeviceData *)DeviceDataPtr;

  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, ExtIntLdd2_PIN_INDEX);
  PORT_PDD_SetPinInterruptConfiguration(PORTA_BASE_PTR,
    ExtIntLdd2_PIN_INDEX, DeviceDataPrv->IrqConfig);
}

/*
** ===================================================================
**     Method      :  ExtIntLdd2_Disable (component ExtInt_LDD)
*/
/*!
**     @brief
**         Disable the component - the external events are not accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void ExtIntLdd2_Disable(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  PORT_PDD_SetPinInterruptConfiguration(PORTA_BASE_PTR,
    ExtIntLdd2_PIN_INDEX, PORT_PDD_INTERRUPT_DMA_DISABLED);
}

/*
** ===================================================================
**     Method      :  ExtIntLdd2_Interrupt (component ExtInt_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void ExtIntLdd2_Interrupt(void)
{
  /* {Default RTOS Adapter} ISR parameter is passed through the global variable */
  ExtIntLdd2_TDeviceDataPtr DeviceDataPrv = INT_PORTA__DEFAULT_RTOS_ISRPARAM;

  /* Check the pin interrupt flag of the shared interrupt */
  if (PORT_PDD_GetPinInterruptFlag(PORTA_BASE_PTR, ExtIntLdd2_PIN_INDEX)) {
    /* Clear the interrupt flag */
    PORT_PDD_ClearPinInterruptFlag(PORTA_BASE_PTR, ExtIntLdd2_PIN_INDEX);
    /* Call OnInterrupt event */
    ExtIntLdd2_OnInterrupt(DeviceDataPrv->UserData);
  }
}

/*
** ===================================================================
**     Method      :  ExtIntLdd2_GetVal (component ExtInt_LDD)
*/
/*!
**     @brief
**         Returns the actual value of the input pin of the component.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Returned input value. Possible values:
**                           <false> - logical "0" (Low level) <true> -
**                           logical "1" (High level)
*/
/* ===================================================================*/
bool ExtIntLdd2_GetVal(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if ((GPIO_PDD_GetPortDataInput(PTA_BASE_PTR) & ExtIntLdd2_PIN_MASK) != 0U) {
    return TRUE;
  } else {
    return FALSE;
  }
}

/*
** ===================================================================
**     Method      :  ExtIntLdd2_SetEdge (component ExtInt_LDD)
*/
/*!
**     @brief
**         Sets the edge type for this component that generates the
**         interrupt.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Edge            - Edge type:
**                           0 - falling edge
**                           1 - rising edge
**                           2 - both edges
**                           3 - low level
**                           4 - high level
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Value is out of range
*/
/* ===================================================================*/
LDD_TError ExtIntLdd2_SetEdge(LDD_TDeviceData *DeviceDataPtr, uint8_t Edge)
{
  ExtIntLdd2_TDeviceData *DeviceDataPrv = (ExtIntLdd2_TDeviceData *)DeviceDataPtr;
  uint32_t Config;

  /* Edge value test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if (Edge > 4U) {
    return ERR_RANGE;                  /* Invalid edge parameter */
  }
  switch (Edge) {
    case 0:                            /* Falling edge */
      Config = PORT_PDD_INTERRUPT_ON_FALLING;
      break;
    case 1:                            /* Rising edge */
      Config = PORT_PDD_INTERRUPT_ON_RISING;
      break;
    case 2:                            /* Both edges */
      Config = PORT_PDD_INTERRUPT_ON_RISING_FALLING;
      break;
    case 3:                            /* Low level */
      Config = PORT_PDD_INTERRUPT_ON_ZERO;
      break;
    case 4:                            /* High level */
      Config = PORT_PDD_INTERRUPT_ON_ONE;
      break;
    default:
      return ERR_RANGE;
  }
  /* Apply the new configuration */
  PORT_PDD_SetPinInterruptConfiguration(PORTA_BASE_PTR, ExtIntLdd2_PIN_INDEX, Config);
  /* Save the new IRQ configuration */
  DeviceDataPrv->IrqConfig = Config;
  return ERR_OK;
}

/* END ExtIntLdd2. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
